### ISSUE TITLE
黒ブロック運搬調整

### ISSUE THREAD

**Issue by kodama0720** [KatLab-MiyazakiUniv/etrobocon2021#110]
## 完了条件
- 黒ブロック運搬を9割以上の精度で成功させる
- 終了状態は手前の黒線上での停止

## 実現方法
- 距離、PWM値、PIDの調整
- 曲線状に走った場合の精度確認・時間計測
- 最低30回動作を確認し、平均時間と最長時間を示す

**Comment by arimakaoru** [comment]
実験するときに、ついでに黒ブロック運搬にかかる時間を計測して、平均時間と最長時間を示してほしい。

**Comment by sugaken0528** [comment]
OKよ

**Comment by hiroto0927** [comment]
黒ブロック運搬ですが、ライントレースで青の部分が二か所あると思うんですが、その部分を今は、StraightRunnerで走らせていると思うんですけど、その部分を青線をライントレースするようにしてほしいです。
研究室の宮下君の環境と自分の環境では、今の状態だと青線の部分が超えられないことが発生していたので、、、

それ以外は良いと思います。

**Comment by mutotaka0426** [comment]
lgtm

**Comment by miyashita64** [comment]
lgtm

**Comment by uchyam** [comment]
LGTM

**Comment by Takahiro55555** [comment]
黒ブロック運搬は、カラーセンサーを使う感じ？
もし使うなら、テストのとき照明環境を変えるようにしたほうが良いと思います。
