### ISSUE TITLE
動作変換

### ISSUE THREAD

**Issue by Hisataka-Hagiyama** [KatLab-MiyazakiUniv/etrobocon2021#111]
## 完了条件
- 動作変換を行うMotionConverterクラスを作成する
- 最短経路からどの動作を行うかを求めるdetermineMotionを作成する
- 方向転換の角度を計算するcaluclateAngleを作成する

## 実現方法
- determineMotionは引数として移動前の向きと移動後の向きを受け取る
- 動作を表すenum classを作成
- 列挙型を戻り値とする

- calculateAngleは引数として移動前の向きと移動後の向きを受け取る
- 角度を戻り値とする

**Comment by arimakaoru** [comment]
## 完了条件
 どんなテストをする？

## 実現方法
- determinMotion関数は，最短経路も引数として受け取る必要がある？
- determinMotion関数が受け取る最短経路は，1つのカラーブロックを運搬する経路？それとも全てのカラーブロックを運搬する経路？

**Comment by mutotaka0426** [comment]
経路計算内で使うから，現在の<座標，方角>と次の<座標，方角>から動作を判定する，publicな関数が欲しい！
determineMotion内でそれを使って動作変換していってもいいし，別にやってもいいし
実現が難しそうなら相談してください

**Comment by Hisataka-Hagiyama** [comment]
テストは、ticket-94で求めた初期配置におけるフルビンゴまでの各ステップを動作に変換できているかをテストしようと思います。

**Comment by miyashita64** [comment]
LGTM

**Comment by hiroto0927** [comment]
LGTM

**Comment by Takahiro55555** [comment]
LGTM

**Comment by sugaken0528** [comment]
経路計算で使う移動コストの算出の方法に関して、今のところ距離で計算してる実コストと推定コストを各動作の**時間コスト**で計算してほしい。
**時間コスト**={(当該動作の平均計測時間(mm)-最小計測時間)/(最大計測時間-最小計測時間)}*(2.0-1.0)+1.0
移動コストに関しては、「推定コスト+実コスト+**誤差コスト**」で計算して欲しい。
**誤差コスト**={(当該動作の平均誤差(deg)-最小誤差)/(最大誤差-最小誤差)}*(1.0-0.0)+0.0

時間コストと誤差コストの式については、時間コストは1.0〜2.0、誤差コストは0.0〜1.0に正規化するための式。
平均計測時間、最大計測時間、最小計測時間、平均誤差、最大誤差、最小誤差に関しては各動作の精度調整が終わり次第計測する予定です。

**Comment by mutotaka0426** [comment]
萩山君と相談して決まった事のまとめです

- 動作変換クラスの`次の動作を求める処理`(シーケンス図参照)は，実装では次のうちのどれかが返ってくる
  - 交点内直進
  - 交点内左折
  - 交点内右折
  - 交点間移動
  - ピボットターン設置
  - 投げ入れ設置
- 経路の定義
  - 最短経路：経路計算で帰ってくる経路（<現在地 - ブロック> or <ブロック - ブロック置き場>）
  - 運搬経路：1つのブロックを取得して設置するまでの経路（）

**Comment by mutotaka0426** [comment]
動作変換の役割は，動作実行を使ってビンゴ動作を呼び出すまでとします．
なので，改めてdetermineMotionは以下のようにお願いします．

- 引数：取得経路 or 設置経路
- 戻り値：void
- テストでは，`期待する動作順序`と`動作実行が持つ履歴`を照合する
