### ISSUE TITLE
動作実行

### ISSUE THREAD

**Issue by Hisataka-Hagiyama** [KatLab-MiyazakiUniv/etrobocon2021#112]
## 完了条件
- MotionPerformerクラスを作成
- 動作を行うactMotionを作成する
- クラスを通してちゃんとビンゴ動作を呼び出せていることを確認できる動画をとる
- 呼び出しに対して正しく履歴を取れてるかのテストをする
- ビンゴ動作クラスにコンストラクタを記述し、動作時間、動作リスクを初期化
- ビンゴ動作クラスを継承するクラスにコンストラクタを記述し、各々の動作時間、動作リスクを初期化する

## 実現方法
- 動作を表すenum classを引数とする
- それに応じた動作を呼び出す
- 動作を記録していく(実現方法は未定)

**Comment by arimakaoru** [comment]
## 完了条件
どんなテストをする？

**Comment by mutotaka0426** [comment]
テストは，このクラスを通してちゃんとビンゴ動作を呼び出せていることを確認できればいいから，動画でいいと思います

テストコードは，呼び出しに対して正しく履歴を取れてるかとかですかね

**Comment by Takahiro55555** [comment]
LGTM

**Comment by hiroto0927** [comment]
LGTM

**Comment by miyashita64** [comment]
LGTM

**Comment by mutotaka0426** [comment]
萩山君と相談して決まった事のまとめです．

動作実行クラスは，全7種類のビンゴ動作に対して，それぞれ次のメソッドを持つ．
  - ビンゴ動作を呼び出して，履歴を取るメソッド
  - ビンゴ動作の時間コストを取得するメソッド
  - ビンゴ動作の誤差コストを取得するメソッド

以上の計21個のメソッドと，呼び出した動作の履歴をフィールドに持つ．

**Comment by mutotaka0426** [comment]
方向転換の履歴の取り方だけど，45度単位で履歴取るようにお願いします．
例えば，45度方向転換をDCとして，135度方向転換するときは，DCを3つ履歴取るようにしてくれればいいです．

つまり，方向転換の履歴を取る処理では，履歴に`指定角度 / 45`回DCを追加すればいいだけだと思います
