### ISSUE TITLE
（試走会）ビンゴエリアの動作確認

### ISSUE THREAD

**Issue by hiroto0927** [KatLab-MiyazakiUniv/etrobocon2021#113]
## 完了条件
ライントレース
↓
黒ブロック運搬
↓
ビンゴエリア内でブロックをブロックサークル内に運搬（今回は、色に指定なし）

期限、　8/1まで

## 実現方法
Etrobocon2021.cpp内に、現状完成しているブロックビンゴエリア攻略クラスから黒ブロック運搬とビンゴ動作を呼びだす。

**Comment by arimakaoru** [comment]
- 試走会の結果をSlackで共有してほしい
- LR両方やる？それともLだけ？

**Comment by sugaken0528** [comment]
ビンゴエリアでのブロックの設置はピボット設置と投げ入れ設置の両方とも試して欲しい。2回の試走で分けてやっても良いけど1回の試走で両方の設置をまとめてできたら試して欲しい。
LR両方ともやりましょう!!

**Comment by mutotaka0426** [comment]
直接指示したけど，手元で動かしたときの動画も取っておいてください

あと，一応共有するためにドラフトプルリク出した方がいいかな
マージはしないから本プルリクにはしないでね

**Comment by Takahiro55555** [comment]
> あと，一応共有するためにドラフトプルリク出した方がいいかな

個人的には、シミュレータテストのバージョンアップ？のために、ゲームエリアを攻略してくれるコードが欲しいのでドラフトプルリクを出してもらえると助かります

**Comment by Hisataka-Hagiyama** [comment]
LGTM

**Comment by kodama0720** [comment]
LGTM

**Comment by uchyam** [comment]
LGTM
