### ISSUE TITLE
アームを水平に保つ処理をタスクに入れる

### ISSUE THREAD

**Issue by hiroto0927** [KatLab-MiyazakiUniv/etrobocon2021#114]
## 完了条件
アームを水平に保つ処理をタスクに入れる。
アームを水平に保つタスクを回してる時に，メインタスクでアーム制御できてることを確認

## 実現方法
前回のイテレーションで作成した、アームを水平に保つ処理を行うファイルをタスク処理のファイルに呼び出す。

## 動作テスト 
ライントレースと各ビンゴ動作を行い、アームが水平に保てているか確認する

**Comment by arimakaoru** [comment]
OK!

**Comment by sugaken0528** [comment]
良いと思います

**Comment by mutotaka0426** [comment]
アームを水平に保つタスクを回してる時に，アーム制御できてることも確認して欲しい

**Comment by Takahiro55555** [comment]
LGTM

**Comment by Hisataka-Hagiyama** [comment]
LGTM

**Comment by kodama0720** [comment]
LGTM

**Comment by uchyam** [comment]
LGTM
