### ISSUE TITLE
回頭・ピボットターンの精度調整

### ISSUE THREAD

**Issue by sugaken0528** [KatLab-MiyazakiUniv/etrobocon2021#131]
## 完了条件
回頭・ピボットターンの誤差を1.5度以下にする。

## 実現方法
緩やかに停止することで、停止時に回転しすぎないようにする。
①現状を測定し、安定して回転できるPWM値を把握
②徐々にPWM値を下げる処理を追加
③修正後の誤差を測定

## 動作テスト 
調整後、回頭・ピボットターンした際の角度の誤差を左右10回ずつ計測する。

**Comment by arimakaoru** [comment]
OK!
去年コードとモデルの工夫点を参考に

**Comment by mutotaka0426** [comment]
lgtm

**Comment by mutotaka0426** [comment]
Assigneesと，zenhubの方でestimateの設定よろしく

**Comment by sugaken0528** [comment]
動作時間も計測お願い
計測用のスプレッドシートに変更を加えといて
