### ISSUE TITLE
ビンゴエリア攻略クラスの実装

### ISSUE THREAD

**Issue by sugaken0528** [KatLab-MiyazakiUniv/etrobocon2021#132]
## 完了条件
- _**本チケットでは【ticket-136 経路計画で求めたフルビンゴの経路をどこかに保持】も実装を行う**_
- ビンゴエリア攻略を行うBingoAreaクラスを作成する(BingoArea)
- ビンゴエリアを走行するstatic関数runBingoAreaを作成する(BingoArea)
- 経路計画内で求めた取得経路、設置経路を保持する(RoutePlanner)
- 保持している経路を返すようにする(RoutePlanner)

## 実現方法
- 経路計画クラスを使い、経路を計画する(BingoArea)
- 動作変換クラスを使い、動作に変換する(BingoArea)
- 配列等を利用し、経路を保持できるようにする(RoutePlanner)

## 関連資料（省略可）

**Comment by arimakaoru** [comment]
LGTM

**Comment by mutotaka0426** [comment]
`経路計画で求めたフルビンゴの経路をどこかに保持`ってissueはこれとまとめて実装してもいいと思うよ
経路計画クラスから帰ってくる経路をここで使うから，分けて実装すると面倒じゃない？任せるけど
