### ISSUE TITLE
BingoAreaクラスをCourseInfoに変更

### ISSUE THREAD

**Issue by sugaken0528** [KatLab-MiyazakiUniv/etrobocon2021#134]
## 完了条件
etrobocon2021/module/CourseInfo/BingoArea.hおよびBingoArea.cppを
CourseInfo.hおよびCourseInfo.cppに変更する

~~##実現方法~~

~~##関連資料（省略可）~~

**Comment by arimakaoru** [comment]
LGTM

**Comment by mutotaka0426** [comment]
lgtm
