### ISSUE TITLE
経路計画で求めたフルビンゴの経路をどこかに保持

### ISSUE THREAD

**Issue by sugaken0528** [KatLab-MiyazakiUniv/etrobocon2021#136]
## 完了条件
- 経路計画内で求めた取得経路、設置経路を保持する
- 保持している経路を返すようにする

## 実現方法
配列等を利用し、経路を保持できるようにする

## **補足**
_**本チケットはticket-132とまとめて実装を行う**_

**Comment by arimakaoru** [comment]
どのクラスが保持するの？

**Comment by mutotaka0426** [comment]
lgtm

**Comment by sugaken0528** [comment]
見ました

**Comment by Hisataka-Hagiyama** [comment]
>どのクラスが保持するの？

経路計画クラスの経路計画を立てる関数内で各取得経路、設置経路を保持し、それをビンゴエリア攻略クラスに渡して動作実行を行うような実装を想定しています
