### ISSUE TITLE
設置動作の改良

### ISSUE THREAD

**Issue by sugaken0528** [KatLab-MiyazakiUniv/etrobocon2021#137]
## 完了条件
- 投げ入れ設置でブロックをサークル内の中央付近に設置できる

## 実現方法
- 回頭の処理と投げ入れの処理を同じループで行う
- 「回頭の精度調整」チケットに合わせて回頭の処理を修正する

## 関連資料（省略可）

**Comment by arimakaoru** [comment]
LGTM

**Comment by mutotaka0426** [comment]
具体的にどういう感じに修正していくのかは分からないけど，ArmMotion弄るならアーム水平処理がおかしくならないように気を付けてね


> 「回頭の精度調整」チケットに合わせて回頭の処理を修正する

これは実現方法じゃない？

**Comment by sugaken0528** [comment]
こちらも動作時間と誤差を計測してスプレッドシートに変更を加えといて欲しい
