### ISSUE TITLE
方向転換の修正

### ISSUE THREAD

**Issue by sugaken0528** [KatLab-MiyazakiUniv/etrobocon2021#142]
## 完了条件
方向転換時、交点内で白を識別し停止する問題の解消。

## 実現方法
方向転換後、色まで直進する処理を追加する。
①現状の、交点内で止まる問題の確認
②色まで直進する処理を追加

## 動作テスト 
調整後、方向転換を行い、交点内で停止しないことを確認する。
3方向につき、10回テストを行う。

**Comment by arimakaoru** [comment]
LGTM

**Comment by mutotaka0426** [comment]
「ブロック設置→方向転換→交点間移動」が正常にできてることも確認して欲しい

**Comment by mutotaka0426** [comment]
Assignees書くのと，zenhubの方でestimateの設定よろしく

**Comment by sugaken0528** [comment]
ナイスー
