### ISSUE TITLE
アームを水平にする処理の修正

### ISSUE THREAD

**Issue by miyashita64** [KatLab-MiyazakiUniv/etrobocon2021#144]
## 完了条件
- 環境によって不安定になる現象の解消。（アームが下がった状態になる場合がある）

## 実現方法
- pidを使わない処理にする

**Comment by arimakaoru** [comment]
PIDを使ってることが原因なの？

**Comment by miyashita64** [comment]
> PIDを使ってることが原因なの？

現象:移動可能状態になってすぐ、アームが引き下げられた状態になる。(補正値が大きすぎる？)

解決したパターン
- シミュレータ起動時のボタンを押されるまでsleepする文の後でアーム水平を有効にする
- アーム水平の処理を終了し、再度実行する（pidがリセット）

推測になりますが、シミュレータ起動から、走行体の操作が可能になるまでの間もアーム水平の処理が実行されており、その間アームが動かないため、pid内で累積している値が異常に大きくなってしまっているのではないかと思います。

目標値との差をpwm値としても、水平に保てていたので、アーム水平のon/offを切り替える処理を加えるよりは、素直にpidを使わない方がいいと思いました。

**Comment by arimakaoru** [comment]
OK!

**Comment by sugaken0528** [comment]
ナイス推測
