### ISSUE TITLE
ライントレースエリアの検証、PID調整

### ISSUE THREAD

**Issue by Hisataka-Hagiyama** [KatLab-MiyazakiUniv/etrobocon2021#59]
## 完了条件

- 現状最速でゴールできるような輝度、PIDゲインの調整を行う

- ゴールするまでのタイム、走破率を測定する

- コースの距離が適切かどうか調査し、必要であれば調整する

 ## 実現方法
- 適切な値が見つかるまで輝度、PIDゲインを変化させる

**Comment by arimakaoru** [comment]
スタートの位置 (座標X,Y,Z) も決定して、みんなに共有してほしい
