### ISSUE TITLE
ビンゴエリアクラス

### ISSUE THREAD

**Issue by Hisataka-Hagiyama** [KatLab-MiyazakiUniv/etrobocon2021#81]
## 完了条件
BingoAreaクラス、Nodeクラス、BlockCircleクラス、crossCircleクラス、CenterMarkクラス、MidPointクラスを作成する
MeasurerクラスにGetCourseInfo関数を作成する
## 実現方法
1.BingoAreaクラス
7*7のビンゴエリア情報を保持
GetBlockInfo関数を用い、ブロックの情報を初期化する関数setBlockInfoを持つ
座標クラスを引数としてブロッククラス（ブロックの情報）を返す関数getBlockInfo関数を持つ
Lコースは左上の座標を(0,0)、Rコースは右上の座標を(0,0)とする

2.Nodeクラス
Block構造体、Coordinate構造体を持つ

3.BlockCircleクラス、crossCircleクラス、CenterMarkクラス
ノードクラスを継承したクラス
Block構造体、Coordinate構造体を持つ
crossCircleクラスは接する黒線の数を保持する

4.Measurerクラス
APIから初期設置情報を取得する

## 関連資料（省略可）
[コース情報の取得](https://github.com/ETrobocon/etrobo/wiki/sim_extended_api)

**Comment by arimakaoru** [comment]
## 動作テスト
- シミュレータ上で、競技規約p28の図6-5「初期配置」の状態にし、適切にBingoAreaクラスを初期化できることを確認する（LR両方）

## テストコード
- シミュレータ用拡張APIの初期設置情報取得関数のdummyを作成し、テストコードで初期化できることをテストする。
初期設置情報取得関数のdummyは、常に競技規約p28の図6-5「初期配置」の状態を返す。

**Comment by mutotaka0426** [comment]
> 全てのクラスはBlock構造体、Coordinate構造体を持つ
これはどういうこと？NodeクラスとNodeクラスを継承しているクラスが持ってるってことではなくて？

**Comment by Hisataka-Hagiyama** [comment]
> 
> 
> > 全てのクラスはBlock構造体、Coordinate構造体を持つ
> 
> これはどういうこと？NodeクラスとNodeクラスを継承しているクラスが持ってるってことではなくて？
