### ISSUE TITLE
運搬先決定

### ISSUE THREAD

**Issue by hiroto0927** [KatLab-MiyazakiUniv/etrobocon2021#84]
## 完了条件
- ブロックの位置情報を受け取り運搬先を決定する。

## 実現方法
運搬先決定クラス(DestinationList)の作成
- コンストラクタ　//運搬先メンバ配列（int destinations[]）を初期化
- getDestination(int blockNumber)   //指定されたブロックの運搬先のサークル番号を返す。

## 関連資料（省略可）
サークル定義
- 黒番号　ブロック番号
- 赤番号　サークル番号
[https://app.zenhub.com/files/362980745/efdf8258-b8b8-4ba2-86be-8fbaf52fffbe/download](https://app.zenhub.com/files/362980745/efdf8258-b8b8-4ba2-86be-8fbaf52fffbe/download)

**Comment by arimakaoru** [comment]
## テストコード
- 競技規約p28の図6-5「初期配置」の状態に対して、適切な運搬先を決定できることを確認する。
- 競技規約p28の図6-5「初期配置」以外で、適当に選んだ4つ以上のパターンに対して、適切な運搬先を決定できることを確認する。

**Comment by arimakaoru** [comment]
「適当に」ではなく、バグが出そうなパターンにする
例
- 同じ距離の場合
