### ISSUE TITLE
運搬ブロック決定

### ISSUE THREAD

**Issue by hiroto0927** [KatLab-MiyazakiUniv/etrobocon2021#86]
## 完了条件
次に運ぶブロックの番号を返す。

## 実現方法
ゲーム走行体クラス(RunningInfo)の作成
- メンバに進行方向（direction）と座標(coordinate)を持つ。
- getDirection()  //進行方向を返す。
- getCoordinate()  //座標を返す。 

運搬ブロック決定クラス(BlockSelector)の作成
- メンバにRunningInfoのインスタンスを持つ
- selectBlockNumber()の作成   //次に運搬するブロックの番号を返す。

**Comment by arimakaoru** [comment]
## テストコード
- 競技規約p28の図6-5「初期設置」の状態から、フルビンゴ成立の状態までをシミュレートし、ブロックの運搬順序が適切であることを確認する

## 具体例
1. ビンゴエリアの初期化
2. 走行体の現在位置の初期化
3. 運搬先の決定
4. 運搬ブロック決定
5. ビンゴエリアクラスのsetter的なのを使って、ブロックを運搬先に移動する
6. フルビンゴ成立でなければ、4に戻る。フルビンゴ成立ならば終了。

**Comment by mutotaka0426** [comment]
> ゲーム走行体クラス(RunningInfo)の作成
> 
> * メンバに進行方向（front）と座標(position)を持つ。
> * getFront()  //進行方向を返す。
> * getposition()  //座標を返す。

座標の名称はビンゴエリアクラスにもあるcoordinateに合わせようか
Coordinateクラス（構造体）のメンバを持つ感じかな？

進行方向っていうのは現在向いている角度のこと？
そうならdirectionとかのほうがいい気がするけど
