### ISSUE TITLE
アームを水平に保つ

### ISSUE THREAD

**Issue by hiroto0927** [KatLab-MiyazakiUniv/etrobocon2021#93]
# 完了条件
アームを水平に保たせる

# 実現方法
アームのクラスを作成。
APIを呼びだして、アームのPWM値を設定。
PIDで調整する。
# 関連資料
改善前

https://user-images.githubusercontent.com/83230897/126026248-0dff9fb2-9fbc-4760-9205-c3088c21027d.mp4

改善後

https://user-images.githubusercontent.com/83230897/126026270-99545eef-28c5-433f-9a10-9d9fd10a4546.mp4

**Comment by Hisataka-Hagiyama** [comment]
アームを水平にする際にPIDの処理を用いる部分がよく分かりません。説明して頂けるとありがたいです。

**Comment by yutotanaka24** [comment]
ｌｇｔｍ

**Comment by hiroto0927** [comment]
- アームを水平にする際にPIDの処理を用いる部分がよく分かりません。説明して頂けるとありがたいです。
→　PID制御は、現在値を目標値にするための出力を最適化する為、モーターの出力調整して水平にできると思い取り入れようと思っています。
