### ISSUE TITLE
経路計算

### ISSUE THREAD

**Issue by Hisataka-Hagiyama** [KatLab-MiyazakiUniv/etrobocon2021#94]
## 完了条件
- 経路探索アルゴリズムを調査し、Etロボコン2021ビンゴエリアで使うのが妥当なものを選定
- 経路計算を行うクラスRouteCalculaterクラスを作成

## 実現方法
- コンストラクタでBingoAreaクラスの参照を受け取る
- 最短経路を計算する関数calculatePathを作成する(引数はスタート地点の座標とゴール地点の座標）
- 最短距離＝現在地からブロックの最短距離＋ブロックから運搬先サークルの最短距離として最短距離を求める
- 各地点での走行体の向きを考慮する

**Comment by arimakaoru** [comment]
分析モデルを作った時点では、どんな風に経路計算をする想定だったかを、 @sugaken0528 @mutotaka0426 に聞いておいて。もちろん、より良い方法を見つけてほしい。

どんなテストをするかを事前に考えておくと、チケットのゴールが明確になって良いと思うよ。

Estimate (見積もりのポイント) を設定して。

**Comment by mutotaka0426** [comment]
> * 最短距離＝現在地からブロックの最短距離＋ブロックから運搬先サークルの最短距離として最短距離を求めるのが良いかどうかを判断する(引数として、スタート地点の座標、中間地点の座標、ゴール地点の座標とするイメージ）

因みに，今のところモデルやRoutePlannerクラスとかでは，「現在地→ブロック」と「ブロック→ブロックサークル」を別々に求める想定になってるよ．
個人的にも，2地点の最短距離を求める処理を作って，「現在地→ブロック」と「ブロック→ブロックサークル」の経路を別々に求めた方が分かりやすいと思うし，テストもしやすいと思う．

スタート地点の座標、中間地点の座標、ゴール地点の座標を引数とするやり方のメリットとしては，「ブロック→ブロックサークル」の時のことも考慮して「現在地→ブロック」の経路を求めることができるってところかな．つまり2つに分けて最短経路を求める場合よりも，厳密な最短経路を求めることができる．他にもメリットがあるかもしれないから要検討ではあるね．

**Comment by Hisataka-Hagiyama** [comment]
コスト＝現在のコスト＋予測距離（マンハッタン距離）とする
（動作コストは本チケットでは考慮しない）

**Comment by Hisataka-Hagiyama** [comment]
### アルゴリズムの選定に関して
**考えたアルゴリズム**　
深さ優先探索(DFS)、幅優先探索(BFS)、ダイクストラ法、A*アルゴリズム

_**結論 A\*アルゴリズム**_
以下判断理由
深さ優先探索、幅優先探索（ダイクストラ法は辺に重みがある場合の幅優先探索）はゴールが分かってもその方向に優先して進むことができないが、A*アルゴリズムではゴールまでの予測距離を使う性質から、ゴールに向かった探索が可能となる。すなわち、ゴールが分かっているならBFSやDFSよりも効率の良い探索ができる。なお、ヒューリスティック関数にマンハッタン距離を使った場合は最短距離であることが保証されるため、最適解を求めることができる。

もし他のアルゴリズムが最適である場合は教えていただけると幸いです。

[Wkipedia A*アルゴリズム](https://ja.wikipedia.org/wiki/A*)
