### ISSUE TITLE
色識別の精度調整

### ISSUE THREAD

**Issue by hiroto0927** [KatLab-MiyazakiUniv/etrobocon2021#95]
## 完了条件
精度の改善と明確化

## 実現方法
①精度の明確化
②パラメータ調整とアルゴリズムの見直し
条件：環境光を変えつつ、アームは水平を保った状態で行う。
③現状と改善後の精度の明確化

**Comment by Hisataka-Hagiyama** [comment]
精度の明確化の際に環境光を考慮した実験を行うとデータの信頼性が増すのかなと思うので、ぜひ環境光を変えて実験して頂きたいです。

**Comment by arimakaoru** [comment]
- どんなテストをするか (つまり、完了条件を具体的に決める) を事前に考えておくと、チケットのゴールが明確になって良いと思うよ。
- どれくらいの精度が必要か、は要検討。現状では、白黒とそれ以外の識別精度が高ければ良いかも？
- 精度を測定するときに使う大量のRGB値を、CSVファイルとかで保存しておくと、回帰テストがしやすいと思う。
