### ISSUE TITLE
直進の精度調整

### ISSUE THREAD

**Issue by hiroto0927** [KatLab-MiyazakiUniv/etrobocon2021#96]
## 完了条件
精度の明確化と改善

## 実現方法
①精度の明確化
②左右のMilage（走行距離）を比較しながら、同じ走行距離になるように、PID制御する。
　ブロックを持った場合、持ってない場合の精度を調べ調整。
③現状と改善後の精度の明確化

**Comment by Hisataka-Hagiyama** [comment]
②の走行距離と照らし合わせるという部分があまり理解できなかったです。

**Comment by arimakaoru** [comment]
- どんなテストをするか (つまり、完了条件を具体的に決める) を事前に考えておくと、チケットのゴールが明確になって良いと思うよ。
- ②がどういうことか、わからない。ミーティングでは、「直進時に左右のブレが大きい」という問題だったよね？その問題に対して、②は有効そうなの？

**Comment by yutotanaka24** [comment]
できれば、ブロックを持った時も誤差が出ているのかなども気になります

**Comment by hiroto0927** [comment]
- チケットのゴールについてですが、距離の誤差はビンゴエリアを3マス分走ってブロックサークルの半径くらいを許容にし、真っ直ぐかは、ビンゴ中の1マスの一辺走って、黒先の幅未満のズレは許容でやろうと思います。

- ②の走行距離と照らし合わせるという部分があまり理解できなかったです。
→実際の距離と設定した距離を比較してどのくらいの誤差があるか検証するということです。

- ②がどういうことか、わからない。ミーティングでは、「直進時に左右のブレが大きい」という問題だったよね？その問題に対して、②は有効そうなの？
→今のところ、PID制御がブレを安定させることに良いのではないかと思いPID制御のクラスでやろうと思っています。
