### ISSUE TITLE
タスク設計をする

### ISSUE THREAD

**Issue by mutotaka0426** [KatLab-MiyazakiUniv/etrobocon2021#98]
## 完了条件
- 必要なタスクの分析
- 空のタスクを実装

## 実現方法
- タスクの実装方法について調査する
- タスク設計を実現できていることを示す動作テストを行う

## 関連資料（省略可）
https://qiita.com/yamanekko/items/7ddb6029820d3cfbd583
https://qiita.com/koushiro/items/22a10c7dd451291fd95b

**Comment by arimakaoru** [comment]
完了条件について
- 実装するのは空のタスクだけなの？「アームを水平に保つタスク」を実装するのかと思ってた。 (本当にそれが必要なのかは要検討)
- 「アームを水平に保つタスク」がある状態で、アームを上げる動作をすると、打ち消し合ったりしないか心配

実現方法について
- タスク設計はEV3RTの機能(?)だと思うから、EV3APIのリファレンスには載っていないと思う。
- EV3RTのWebページ、もしくは技術教育の資料辺りに書いてそう。
- たぶん、2019年にタスク分けをしているから、2019年のコードも参考になると思う。**(必ず公式情報を確認してほしいけど)**

**Comment by mutotaka0426** [comment]
> * 実装するのは空のタスクだけなの？「アームを水平に保つタスク」を実装するのかと思ってた。 (本当にそれが必要なのかは要検討)
> * 「アームを水平に保つタスク」がある状態で、アームを上げる動作をすると、打ち消し合ったりしないか心配

前回の反省から，別のチームのチケットと依存関係があるチケットにはあまりしたくないなってことで完了条件には書かなかったんですけど，書いた方がいいですか？
もちろん，アームを水平に保つ処理が早めにできているならそれを実際に使ってみて，動作テストしてみようと思いますが，とりあえずタスク設計ができる状態を完了条件にしようかなって今のところ思っています．
